baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "PaperMod"
paginate = 10

[params]
  author = "Rahul Sharma"
  description = "My personal blog built with Hugo and PaperMod"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto" # dark, light, auto

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
[taxonomies]
  tag = "tags"
  category = "categories"
